---
current_trade_data:
  every: '10s'
  class: CurrentTradeData
  queue: high_priority
  args:
  description: "Retrieves the current trade values."
control_bot:
  every: '60s'
  class: ControlBot
  queue: default
  args:
  description: "A baseline trading bot."
