---
current_trade_data:
  every: '15s'
  class: CurrentTradeData
  queue: high_priority
  args:
  description: "Retrieves the current trade values."
control_bot:
  every: '60s'
  class: ControlBot
  queue: default
  args:
  description: "A baseline trading bot."
polynomial_bot:
  every: '60s'
  class: PolynomialBestFitBot
  queue: default
  args:
  description: "A more advanced trading bot."
